/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable

import _app from '@/libs/app-context'
export {}
declare global {
  const Block: typeof import('@/components/index')['Block']
  const Button: typeof import('@/components/index')['Button']
  const Checkbox: typeof import('@/components/index')['Checkbox']
  const Container: typeof import('@/components/index')['Container']
  const Content: typeof import('@/components/index')['Content']
  const DataGrid: typeof import('@/components/index')['DataGrid']
  const Editor: typeof import('@/components/index')['Editor']
  const Form: typeof import('@/components/index')['Form']
  const Fragment: typeof import('@/components/index')['Fragment']
  const Image: typeof import('@/components/index')['Image']
  const Input: typeof import('@/components/index')['Input']
  const Link: typeof import('@/components/index')['Link']
  const Lottie: typeof import('@/components/index')['Lottie']
  const Modal: typeof import('@/components/index')['Modal']
  const Page: typeof import('@/components/index')['Page']
  const Pagination: typeof import('@/components/index')['Pagination']
  const React: typeof import('react')['default']
  const Select: typeof import('@/components/index')['Select']
  const Slider: typeof import('@/components/index')['Slider']
  const Spinner: typeof import('@/components/index')['Spinner']
  const Textarea: typeof import('@/components/index')['Textarea']
  const app: typeof _app
  const getLogger: typeof app.getLogger
  const definePage: typeof app.definePage
  const useSetup: typeof app.useSetup
  const goPage: typeof app.goPage
  const getParameter: typeof app.getParameter
  const asType: typeof app.asType
  const useRef: typeof app.useRef
}