/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable

import type * as form from '@/components/form'
import crypto from '@/libs/crypto'

export {}
declare global {
  /** 컴포넌트 등록 (새컴포넌트 작성시 macro-loader.js 도 수정해 주어야 함) */
  const Block: typeof import('@/components/index')['Block']
  const Button: typeof import('@/components/index')['Button']
  const Checkbox: typeof import('@/components/index')['Checkbox']
  const Container: typeof import('@/components/index')['Container']
  const Content: typeof import('@/components/index')['Content']
  const DataGrid: typeof import('@/components/index')['DataGrid']
  const EditorClassic: typeof import('@/components/index')['EditorClassic']
  const Editor: typeof import('@/components/index')['Editor']
  const Form: typeof import('@/components/index')['Form']
  const Fragment: typeof import('@/components/index')['Fragment']
  const Image: typeof import('@/components/index')['Image']
  const Input: typeof import('@/components/index')['Input']
  const Link: typeof import('@/components/index')['Link']
  const Lottie: typeof import('@/components/index')['Lottie']
  const Modal: typeof import('@/components/index')['Modal']
  const Page: typeof import('@/components/index')['Page']
  const Pagination: typeof import('@/components/index')['Pagination']
  const Portal: typeof import('@/components/index')['Portal']
  const Select: typeof import('@/components/index')['Select']
  const Slider: typeof import('@/components/index')['Slider']
  const Spinner: typeof import('@/components/index')['Spinner']
  const Textarea: typeof import('@/components/index')['Textarea']

  /** 공통상수 선언 */
  const C: typeof import('@/libs/constants')

  /**  기타 지역상수 선언 */
  const $PAGENAME$: string

  /** 라이브러리 임포트 */
  const app: typeof import('@/libs/app-context')['default']
  const api: typeof import('@/libs/api')['default']
  const format: typeof import('@/libs/format')['default']
  const values: typeof import('@/libs/values')['default']
  const dialog: typeof import('@/libs/dialog-context')['default']
  const userContext: typeof import('@/libs/user-context')['default']

  /** app 종속 메소드 선언 (수정시 macro-loader.js 도 같이 수정해 주어야 함) */
  const $t: typeof app.$t
  const asAny: typeof app.asAny
  const asType: typeof app.asType
  const basepath: typeof app.basepath
  const changeLang: typeof app.changeLang
  const clear: typeof app.clear
  const clone: typeof app.clone
  const defineComponent: typeof app.defineComponent
  const definePage: typeof app.definePage
  const getFrom: typeof app.getFrom
  const getGlobalTmp: typeof app.getGlobalTmp
  const getLogger: typeof app.getLogger
  const getOpenerTmp: typeof app.getOpenerTmp
  const getParameter: typeof app.getParameter
  const getText: typeof app.getText
  const getUri: typeof app.getUri
  const getUrl: typeof app.getUrl
  const goPage: typeof app.goPage
  const isClient: typeof app.isClient
  const isServer: typeof app.isServer
  const log: typeof app.log
  const matcher: typeof app.matcher
  const merge: typeof app.merge
  const modelValue: typeof app.modelValue
  const profile: typeof app.profile
  const pushAll: typeof app.pushAll
  const putAll: typeof app.putAll
  const px2rem: typeof app.px2rem
  const randomStr: typeof app.randomStr
  const rem2px: typeof app.rem2px
  const setGlobalTmp: typeof app.setGlobalTmp
  const setOpenerTmp: typeof app.setOpenerTmp
  const sleep: typeof app.sleep
  const strm: typeof app.strm
  const toJSON: typeof app.toJSON
  const toString: typeof app.toString
  const until: typeof app.until
  const useGlobalRef: typeof app.useGlobalRef
  const useRef: typeof app.useRef
  const useSetup: typeof app.useSetup

  /** 암복호화 관련 */
  const encrypt: typeof crypto.aes.encrypt
  const decrypt: typeof crypto.aes.decrypt

  /** 폼관련 */
  const useForm: typeof form.useForm
  const validateForm: typeof form.validateForm
}